<a href="https://colab.research.google.com/github/KimyYoungWook/DataScience/blob/main/%EB%8D%B0%EC%9D%B4%EB%B8%94%ED%98%95%EC%88%98%EC%B9%98%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

10개의 양수로 된 간단한 numpy 배열 만들기

In [ ]:
import numpy as np
numbers02 = np.array(range(1,11),copy =True)

ones() -> 1,zeros() -> 0,empty() ->  아직생성되지 않은 엔트리로 구성<br> 
#https://numpy.org/doc/stable/reference/generated/numpy.array.html  numpy doc

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움
ones = np.ones([2,4] ,dtype=np.float64)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 0로 채움
zeros = np.zeros([2,4],dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열
empty = np.empty([2,4],dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

데이터 확인하기

In [ ]:
ones.shape # 행렬 크기

(2, 4)

In [ ]:
ones.ndim # 행의 크기

2

In [ ]:
ones.dtype #데이터 타입 확인

dtype('float64')

arange(start, stop, step, dtype=None) 일정 간격으로 배열 생성하는 함수


In [ ]:
np_numbers = np.arange(2,5,0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

astype(dtype, casting="unsafe", copy=True) 아이템의 타입 변경해 주는 함수


In [ ]:
np_numbers =np_numbers.astype(np.int)
np_numbers.dtype

dtype('int64')

reshape(d0,d1,....)대상 배열의 모양을 바꿔주는 함수


In [ ]:
# 몇 가지 S&P 주식 기호들
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap #U4 는 4글자 유니코드 

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
sap.shape

(8,)

In [ ]:
sap2d= sap.reshape(2,4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
# 기존 배열과 새로운 배열의 아이템의 개수는 항상 동일 해야 함
# numpy 보존의 법칙 성립
sap3d =sap.reshape(2,2,2)
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
sap3d[0] # 1차원

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [ ]:
sap3d[1]# 2차원

array([['ACE', 'ATVI'],
       ['ADBE', 'ADT']], dtype='<U4')

데이터 클리닝(data cleaning)을 위해 사용 되는 boolean indexing


In [ ]:
# 절대 음수 값이 와서는 안되는 데이터셋
dirty =np.array([9,4,1,-0.01,-0.02,-0.001])
whos_dirty = dirty < 0 
dirty[whos_dirty] = 0
dirty

array([9., 4., 1., 0., 0., 0.])

논리 연산자 | or, & and, - not 결합하여 boolean indexing 사용


In [ ]:
linear = np.arange(-1.1,1,0.2)
linear

array([-1.1, -0.9, -0.7, -0.5, -0.3, -0.1,  0.1,  0.3,  0.5,  0.7,  0.9])

In [ ]:
#-0.5 ~0.5 사이의 값만 -> 0으로 변경하고 싶음
whos_linear = (linear >=-0.5) & (linear <=0.5)

In [ ]:
linear[whos_linear]

array([-0.3, -0.1,  0.1,  0.3,  0.5])

In [ ]:
sap[[1,2,-1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [ ]:
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
sap2d[:,[2]]

array([['ABBV'],
       ['ADBE']], dtype='<U4')

차원만 같다면 numpy에서는 사칙연산 가능 (그낭 더하기) -> 브로드캐스팅


In [ ]:
a = np.arange(4)
b = np.arange(1,5)
print(a)
print(b)

[0 1 2 3]
[1 2 3 4]


In [ ]:
a+b

array([1, 3, 5, 7])

In [ ]:
noise = np.eye(4)
noise

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
noise = np.eye(4) + 0.01*np.random.random([4,4])
noise

array([[1.00208568e+00, 3.02990869e-03, 5.68195860e-03, 8.57482146e-04],
       [1.22651074e-03, 1.00134761e+00, 8.28583067e-03, 6.54898397e-03],
       [3.43368414e-03, 7.70848407e-03, 1.00460226e+00, 5.35182617e-03],
       [1.69975786e-03, 8.61018201e-03, 1.98374506e-03, 1.00209001e+00]])